#!/bin/sh
#PBS -N mathematica
#PBS -W umask=022
#PBS -j oe
#PBS -l ncpus=12
#PBS -l mem=4gb
#PBS -m abe
#PBS -M stanay@go.olemiss.edu


module load mathematica

cd $PBS_O_WORKDIR
math -script 0PN_e0_4_dropped.m
math -script 0PN_e0_2_dropped.m
math -script 0PN_e0_0_dropped.m
math -script 1PN_e0_4_dropped.m
math -script 1PN_e0_2_dropped.m
math -script 1PN_e0_0_dropped.m
math -script 1.5PN_e0_4_dropped.m
math -script 1.5PN_e0_2_dropped.m
math -script 1.5PN_e0_0_dropped.m
